# Generated by Django 6.0 on 2026-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=120)),
                ('facility_type', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=80)),
                ('province', models.CharField(max_length=80)),
            ],
        ),
    ]
