# Generated by Django 6.0 on 2026-02-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthposts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=30)),
                ('quantity_available', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthposts.healthpost')),
            ],
        ),
    ]
